### PR TITLE
Add test for Enumerable methods

### PR DESCRIPTION
**Pull request by Misori-simon**
# Added test for:
- my_each
- my_each_with_index
- my_select
- my_all?
- my_any?
- my_none?
- my_count
- my_map 
- my_inject

### CODE REVIEW

**Review by ElijahTobs — CHANGES_REQUESTED** [review]
# Status: Changes Required :recycle: 

### Hi @Misori-simon and @Lameck1 

You two have done well so far but there's a little more to be done before this milestone can be approved.

## [REQUIRED]
- [ ] Remove all unnecessary comments in your test.rb file
- [ ] The overuse of rubocop disable cops comments in your **enumerable.rb** file is a bad practice. 
- [ ] You completely disabled rubocop in your **test.rb** file. Please, enable it and fix all errors.

### Make the required changes and submit for another review. :muscle: 

## Happy Coding :computer: 

_Feel free to reach out to me on slack_ **`@Elijah Ayandokun`**
  **Elijah O. Ayandokun**
[Github](https://github.com/ElijahTobs) | [LinkedIn](https://www.linkedin.com/in/ayandokunelijah/) | [Twitter](https://twitter.com/ElijahTobs)

**Comment by Lameck1** [comment]
Hello @ElijahTobs, hope you are well, and thanks for the review.
I have the feeling that the changes you have requested could have come as suggestions.
This PR is not concerned with the files you've checked, it's primarily on writing tests for the custom enumerable methods.
The file you have issues with can be entirely deleted and it will not affect the project in any way, it was just for testing the methods. Please, give us a review based on the requirements of the project. Which is implementing tests for methods we wrote some time back which had already been approved in a former project: ruby enumerables.

We are going to ask for another review, we just wanna know if we are implementing tests correctly or not.

Thanks.

**Review by Temmarie — CHANGES_REQUESTED** [review]
### Changes Required! :recycle:
Hi @Misori-simon and @Lameck1  !

### You have done well so far :clap: However, you did not finish all the previous review changes. Kindly work on them and submit them for another code review.

**Recommended** 
 - [ ] Remove all unnecessary comments in your test.rb file.

 - [ ] You have overused the rubocop disable cops in your enumerable.rb file. It's considered bad practice, please remove it and find ways to fix the errors.

 - [ ] You completely disabled rubocop in your test.rb file. Please, enable it and fix all errors.

_**Now, regarding the request, you made earlier. Your tests run perfectly well and are concise without errors.  I understand the test.rb file could have been for learning purposes, however, that should not be added in the project at all. It should have been deleted from the start. If you needed to add it, then you should have stated in the PR message that the file is merely for learning purposes and will be removed after the review. 
Also, next time you have issues with a review given by a TSE, be sure to message them privately on slack and complain about it, that's why we leave our contacts at the end of the reviews so you can reach out to us. When you leave comments here on Github, there's no guarantee that the TSE will respond to it.**_

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Review by Temmarie — APPROVED** [review]
## Status: Approved :heavy_check_mark:

### Hi @Misori-simon and @Lameck1 ! 👋 👋 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: :tada:

### You may merge, good luck with your next projects! :rocket:
### Happy Coding! :+1:
__Grace Tamara Ekunola __
[GitHub](https://github.com/temmarie) | [LinkedIn](https://www.linkedin.com/in/ekunola-grace/) | [Twitter](https://twitter.com/TemmarieW)

**Pull request merged**
