### PR TITLE
Enumerable methods to merge in develop branch

### PR DESCRIPTION
**Pull request by smcommits**
**Project Description**

In this project, we have implemented some of the ruby's magical enumerable methods. 

**Key Points**

In this project, we have implemented the following enumerable methods:

    each method as my_each
    each_with_index as my_each_with_index
    _select as my_select
    all? as my_all?
    any? as my_any?
    none? as my_none?
    count as my_count
    map as my_map
    inject as my_inject
    multiply_els this is our own method to test the my_inject method

### CODE REVIEW

**Comment by mimipeshy** [comment]
## STATUS :CHANGES REQUIRED :red_circle: 

Hi team :wave: , this is good work you did and most methods work, except some methods still need some work, lets fix them :smile: 

- [x] should have working my_any?  identical and returns the same thing as ruby's 
[`any?`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-any-3F). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_any.png) from [Odin](https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/archive/basic_ruby/project_advanced_building_blocks.md#project-2-enumerable-methods))

-  enumerables #my_any? when no block or argument is given returns true if at least one of the collection is not false or nil. Yours returns a false

- [x] should have working `my_count` identical and returns the same thing as ruby's [`count`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-count). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_count.png) from [Odin](https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/archive/basic_ruby/project_advanced_building_blocks.md#project-2-enumerable-methods))

- enumerables #my_count returns the number of items in enum through enumeration::range

- [x] should have working `my_map` identical and returns the same thing as ruby's [`map`](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-map). ([Screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/advanced_building_blocks_enumerable/my_map.png) from [Odin](https://github.com/TheOdinProject/curriculum/blob/master/ruby_programming/archive/basic_ruby/project_advanced_building_blocks.md#project-2-enumerable-methods))
- enumerables #my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.

Thats it :relieved:  , feel free to reach out to me incase of any questions on slack (peris ndanu)
Submit another form for review when you are done.

Peris Ndanu

**Comment by kelvin8773** [comment]
# Status: Change Required :broken_heart:

Hi, Team, :wave:

You fixed 2 errors but still have one more to go ... 👍 

- [x] should have working my_map **(covered by automated tests)** identical and returns the same thing as ruby's [map](https://ruby-doc.org/core-2.6.4/Enumerable.html#method-i-map).

### Please check the following tips for your reference: 
- return call 'proc' result instead of `element` in array. (check the code below)
```ruby
>> [2, 3, 4, 5, 19, 11, 8, 6].map { |num| num % 2 == 0 }
=> [true, false, true, false, false, false, true, true]
```
- give a default value to `proc`.

Please feel free to reach me at Slack [Kelvin Liang] if there is anything unclear.

Try harder and good luck! 💪  💪  💪 

Best,
Kelvin

**Comment by smcommits** [comment]
@kelvin8773 Thank you so much for the feedback! 
I am afraid I don't completely understand the change that you have requested. As **my_map** method and the actual **map** method return the same output upon running your test case. Can you please elaborate on the issue? 
[The screenshot of the output](https://imgur.com/a/HyPZcMs)

**Comment by kelvin8773** [comment]
> @kelvin8773 Thank you so much for the feedback!
> I am afraid I don't completely understand the change that you have requested. As **my_map** method and the actual **map** method return the same output upon running your test case. Can you please elaborate on the issue?
> [The screenshot of the output](https://imgur.com/a/HyPZcMs)

Sorry, I just checked, I missed the last commit @Misori-simon made, so that problem is fixed.

But the method still leaves one issue to fix - which is the last requirement indicated in [project instruction](https://github.com/TheOdinProject/curriculum/blob/master/archive/old_lessons/ruby/basic_ruby/project_advanced_building_blocks.md#project-2-enumerable-methods).

> 14. Modify your #my_map method to take either a proc or a block. It won't be necessary to apply both a proc and a block in the same #my_map call since you could get the same effect by chaining together one #my_map call with the block and one with the proc. This approach is also clearer, since the user doesn't have to remember whether the proc or block will be run first. **So if both a proc and a block are given, only execute the proc.**

* Please note - this requirement will not work on normal `map` method in ruby, but it is required in this project to show your skill of ruby language.

**Comment by Misori-simon** [comment]
> > @kelvin8773 Thank you so much for the feedback!
> > I am afraid I don't completely understand the change that you have requested. As **my_map** method and the actual **map** method return the same output upon running your test case. Can you please elaborate on the issue?
> > [The screenshot of the output](https://imgur.com/a/HyPZcMs)
> 
> Sorry, I just checked, I missed the last commit @Misori-simon made, so that problem is fixed.
> 
> But the method still leaves one issue to fix - which is the last requirement indicated in [project instruction](https://github.com/TheOdinProject/curriculum/blob/master/archive/old_lessons/ruby/basic_ruby/project_advanced_building_blocks.md#project-2-enumerable-methods).
> 
> > 1. Modify your #my_map method to take either a proc or a block. It won't be necessary to apply both a proc and a block in the same #my_map call since you could get the same effect by chaining together one #my_map call with the block and one with the proc. This approach is also clearer, since the user doesn't have to remember whether the proc or block will be run first. **So if both a proc and a block are given, only execute the proc.**
> 
> * Please note - this requirement will not work on normal `map` method in ruby, but it is required in this project to show your skill of ruby language.

Okay. We will see to that.

**Review by umairarshadbutt — APPROVED** [review]
# **Status: PROJECT APPROVED** :champagne:
Excellent job on this project guys. :fireworks: Keep it up.
##
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @Misori-simon and @smcommits ! :+1: 
- You can now merge to master and submit the project completion form :rocket: . I wish you all the very best in your next tasks :1st_place_medal:
##
**If you have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

**Pull request merged**
